"""core domain: courses, members, bookings, waitlist, checkin, training, notifications, automation, insights, events

Revision ID: 94dfbcb0d1fe
Revises: b88fb036b7a2
Create Date: 2026-07-07 22:04:15.931568

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.types

revision: str = '94dfbcb0d1fe'
down_revision: str | None = 'b88fb036b7a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('type', sa.Enum('FORECAST', 'RECOMMENDATION', 'ANOMALY', 'ASSISTANT_ANSWER', name='insighttype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_insights_tenant_id'), 'ai_insights', ['tenant_id'], unique=False)
    op.create_table('automation_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.Enum('INACTIVE_DAYS', 'AFTER_BOOKING', 'BEFORE_SESSION', 'AFTER_NO_SHOW', 'MEMBERSHIP_EXPIRING', name='automationtrigger', native_enum=False, length=32), nullable=False),
    sa.Column('threshold_days', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('PUSH', 'WHATSAPP', 'EMAIL', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_rules_tenant_id'), 'automation_rules', ['tenant_id'], unique=False)
    op.create_table('rooms',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_tenant_id'), 'rooms', ['tenant_id'], unique=False)
    op.create_table('training_requirements',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('area', sa.Enum('PRACTICE', 'OBSERVATION', 'MEDITATION', 'THEORY', 'TEACHING', 'OTHER', name='trainingarea', native_enum=False, length=20), nullable=False),
    sa.Column('required_hours', sa.Float(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_requirements_tenant_id'), 'training_requirements', ['tenant_id'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('level', sa.Enum('ALL', 'BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='courselevel', native_enum=False, length=32), nullable=False),
    sa.Column('room_id', app.db.types.GUID(), nullable=True),
    sa.Column('teacher_id', app.db.types.GUID(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_tenant_id'), 'courses', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('WORKSHOP', 'RETREAT', 'SPECIAL', name='eventtype', native_enum=False, length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('requires_deposit', sa.Boolean(), nullable=False),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('teacher_id', app.db.types.GUID(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_tenant_id'), 'events', ['tenant_id'], unique=False)
    op.create_table('members',
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('membership_type', sa.Enum('DROP_IN', 'PUNCH_CARD', 'UNLIMITED', 'NONE', name='membershiptype', native_enum=False, length=20), nullable=False),
    sa.Column('membership_valid_until', sa.Date(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('avg_response_seconds', sa.Integer(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=False)
    op.create_index(op.f('ix_members_tenant_id'), 'members', ['tenant_id'], unique=False)
    op.create_table('course_sessions',
    sa.Column('course_id', app.db.types.GUID(), nullable=False),
    sa.Column('teacher_id', app.db.types.GUID(), nullable=True),
    sa.Column('room_id', app.db.types.GUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('overbooking_allowance', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='sessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_sessions_course_id'), 'course_sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_sessions_starts_at'), 'course_sessions', ['starts_at'], unique=False)
    op.create_index(op.f('ix_course_sessions_tenant_id'), 'course_sessions', ['tenant_id'], unique=False)
    op.create_table('event_registrations',
    sa.Column('event_id', app.db.types.GUID(), nullable=False),
    sa.Column('member_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'WAITLISTED', name='eventregistrationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=False),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_registrations_event_id'), 'event_registrations', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_member_id'), 'event_registrations', ['member_id'], unique=False)
    op.create_index(op.f('ix_event_registrations_tenant_id'), 'event_registrations', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('member_id', app.db.types.GUID(), nullable=True),
    sa.Column('channel', sa.Enum('PUSH', 'WHATSAPP', 'EMAIL', name='notificationchannel', native_enum=False, length=20), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'READ', name='notificationstatus', native_enum=False, length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('template', sa.String(length=120), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_member_id'), 'notifications', ['member_id'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_table('attendance',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('member_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'EXCUSED', 'LATE', name='attendancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('recorded_by', app.db.types.GUID(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_member_id'), 'attendance', ['member_id'], unique=False)
    op.create_index(op.f('ix_attendance_session_id'), 'attendance', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_tenant_id'), 'attendance', ['tenant_id'], unique=False)
    op.create_table('bookings',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('member_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('BOOKED', 'CANCELLED', 'ATTENDED', 'NO_SHOW', name='bookingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('source', sa.Enum('DIRECT', 'DROP_IN', 'WAITLIST', 'REBOOKED', name='bookingsource', native_enum=False, length=20), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'member_id', name='uq_booking_session_member')
    )
    op.create_index(op.f('ix_bookings_member_id'), 'bookings', ['member_id'], unique=False)
    op.create_index(op.f('ix_bookings_session_id'), 'bookings', ['session_id'], unique=False)
    op.create_index(op.f('ix_bookings_tenant_id'), 'bookings', ['tenant_id'], unique=False)
    op.create_table('training_hours',
    sa.Column('trainee_id', app.db.types.GUID(), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=True),
    sa.Column('teacher_id', app.db.types.GUID(), nullable=True),
    sa.Column('area', sa.Enum('PRACTICE', 'OBSERVATION', 'MEDITATION', 'THEORY', 'TEACHING', 'OTHER', name='trainingarea', native_enum=False, length=20), nullable=False),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_hours_tenant_id'), 'training_hours', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_hours_trainee_id'), 'training_hours', ['trainee_id'], unique=False)
    op.create_table('waitlist_entries',
    sa.Column('session_id', app.db.types.GUID(), nullable=False),
    sa.Column('member_id', app.db.types.GUID(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'OFFERED', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='waitliststatus', native_enum=False, length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('offered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_entries_member_id'), 'waitlist_entries', ['member_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_session_id'), 'waitlist_entries', ['session_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_tenant_id'), 'waitlist_entries', ['tenant_id'], unique=False)
    op.create_table('check_ins',
    sa.Column('member_id', app.db.types.GUID(), nullable=False),
    sa.Column('session_id', app.db.types.GUID(), nullable=True),
    sa.Column('booking_id', app.db.types.GUID(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('method', sa.Enum('QR', 'NFC', 'MANUAL', 'KIOSK', name='checkinmethod', native_enum=False, length=20), nullable=False),
    sa.Column('device_id', sa.String(length=120), nullable=True),
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('tenant_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['course_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_member_id'), 'check_ins', ['member_id'], unique=False)
    op.create_index(op.f('ix_check_ins_session_id'), 'check_ins', ['session_id'], unique=False)
    op.create_index(op.f('ix_check_ins_tenant_id'), 'check_ins', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_ins_tenant_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_session_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_member_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_waitlist_entries_tenant_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_session_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_member_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index(op.f('ix_training_hours_trainee_id'), table_name='training_hours')
    op.drop_index(op.f('ix_training_hours_tenant_id'), table_name='training_hours')
    op.drop_table('training_hours')
    op.drop_index(op.f('ix_bookings_tenant_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_member_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_attendance_tenant_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_session_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_member_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_member_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_event_registrations_tenant_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_member_id'), table_name='event_registrations')
    op.drop_index(op.f('ix_event_registrations_event_id'), table_name='event_registrations')
    op.drop_table('event_registrations')
    op.drop_index(op.f('ix_course_sessions_tenant_id'), table_name='course_sessions')
    op.drop_index(op.f('ix_course_sessions_starts_at'), table_name='course_sessions')
    op.drop_index(op.f('ix_course_sessions_course_id'), table_name='course_sessions')
    op.drop_table('course_sessions')
    op.drop_index(op.f('ix_members_tenant_id'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_events_tenant_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_courses_tenant_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_training_requirements_tenant_id'), table_name='training_requirements')
    op.drop_table('training_requirements')
    op.drop_index(op.f('ix_rooms_tenant_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_automation_rules_tenant_id'), table_name='automation_rules')
    op.drop_table('automation_rules')
    op.drop_index(op.f('ix_ai_insights_tenant_id'), table_name='ai_insights')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
